#!/usr/bin/env python3
"""Read-only audit of the three formal EE blockwise execution contracts.

The functional re-audit permits calibrated per-EE straight wz and per-EE
stopping-distance estimates. Everything else in the runtime contract must be
common. This script checks both the resolved contracts generated by the
runner and the source-level variant branches, without starting Isaac Sim.
It deliberately does not edit or reinterpret the historical response files.
"""

from __future__ import annotations

import argparse
import ast
import copy
import hashlib
import json
from pathlib import Path
import sys
from typing import Any, Mapping

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO / "scripts"))

from falcon_g1.half_meter_assets import (  # noqa: E402
    ASSET_SPECS,
    asset_path,
    composed_fixed_joint_closure,
    composed_rubber_hand_mass,
    sha256_file,
    validate_frozen_files,
)
from falcon_g1.half_meter_executor import (  # noqa: E402
    FORMAL_EE_VARIANTS,
    NOMINAL_SPEED_MPS,
    PHYSICS_DT_S,
    CONTROL_DECIMATION,
    OFFICIAL_FALCON_SHA256,
    Q_UPPER_SHA256,
    RUBBER_HAND_MASS_PER_SIDE_KG,
)
from run_functional_blockwise_trial import (  # noqa: E402
    FALCON_ONNX,
    Q_UPPER_PATH,
    make_contract,
)


RUNNER = REPO / "scripts/run_functional_blockwise_trial.py"
BASELINE_RUNNER = REPO / "scripts/run_functional_symmetry_baseline.py"


def canonical(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(k): canonical(v) for k, v in sorted(value.items(), key=lambda item: str(item[0]))}
    if isinstance(value, (list, tuple)):
        return [canonical(item) for item in value]
    if isinstance(value, np.ndarray):
        return canonical(value.tolist())
    if isinstance(value, (float, np.floating)):
        number = float(value)
        return round(number, 12) if np.isfinite(number) else None
    if isinstance(value, (int, np.integer, bool)) or value is None or isinstance(value, str):
        return value
    return str(value)


def digest(value: Any) -> str:
    encoded = json.dumps(canonical(value), sort_keys=True, separators=(",", ":"), allow_nan=False).encode()
    return hashlib.sha256(encoded).hexdigest()


def normalized_contract(value: Mapping[str, Any]) -> dict[str, Any]:
    """Remove only explicitly permitted EE-specific fields."""

    result = copy.deepcopy(dict(value))
    for key in ("formal_ee", "trial_id", "asset", "reset_posture_gate", "contact_contract", "asset_composed_audit"):
        result.pop(key, None)
    command = result.get("command_contract")
    if isinstance(command, dict):
        # This is a measured/calibrated per-EE action parameter, not a
        # different path/controller/physics stack.
        command.pop("straight_wz_radps", None)
    stop = result.get("stop_contract")
    if isinstance(stop, dict):
        stop.pop("d_stop_hat_initial_m", None)
    return result


def formal_branches(path: Path) -> list[dict[str, Any]]:
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    result: list[dict[str, Any]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.If):
            text = ast.get_source_segment(source, node.test) or ""
            if "formal_ee" in text:
                result.append({"line": node.lineno, "condition": text.strip()})
    return sorted(result, key=lambda item: item["line"])


def source_path_calls(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name):
                names.append(node.func.id)
            elif isinstance(node.func, ast.Attribute):
                names.append(node.func.attr)
    return names


def make_synthetic_contracts(frozen: Mapping[str, Any], baseline: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    choices = {
        "WRIST_ONLY": (0.0, 0.0375821590423584),
        "RUBBER_HAND_NATURAL": (0.12, 0.0625607967376709),
        "RUBBER_HAND_PALM_FORWARD_DOWN_V2": (0.0, 0.03675389289855957),
    }
    result: dict[str, dict[str, Any]] = {}
    for formal in FORMAL_EE_VARIANTS:
        straight_wz, d_stop = choices[formal]
        args = argparse.Namespace(
            formal_ee=formal,
            trial_id="contract-audit",
            seed=42,
            target_m=5.0,
            timeout_s=75.0,
            straight_wz=straight_wz,
            d_stop_initial=d_stop,
            posture_baseline=REPO / "SYMMETRY_BASELINE_P99.json",
        )
        result[formal] = make_contract(
            args,
            frozen,
            asset_path(REPO, formal),
            np.zeros(14, dtype=np.float32),
            baseline,
        )
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--provenance-reference",
        type=Path,
        default=Path(
            "/root/autodl-tmp/robotics/runs/"
            "falcon_half_meter_measured_response_blockwise_20260831/"
            "asset_provenance_audit_v3/audit.json"
        ),
    )
    args = parser.parse_args()
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    frozen = validate_frozen_files(REPO)
    baseline = {"link_p99_envelope": {"audit": {}}}
    contracts = make_synthetic_contracts(frozen, baseline)
    normalized = {formal: normalized_contract(contract) for formal, contract in contracts.items()}
    normalized_hashes = {formal: digest(value) for formal, value in normalized.items()}

    # The bundled Isaac environment exposes pxr through AppLauncher.  No
    # stage is simulated or stepped here; the launcher is only used to make
    # the composed-USD read-only property audit available.
    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, enable_cameras=False).app

    branches = formal_branches(RUNNER)
    allowed_branch_fragments = (
        "ASSET_SPECS[args.formal_ee].has_rubber_hand",
        'args.formal_ee == "WRIST_ONLY"',
        'args.formal_ee != "WRIST_ONLY"',
        'args.formal_ee == "RUBBER_HAND_PALM_FORWARD_DOWN_V2"',
    )
    branch_policy_pass = bool(branches) and all(
        any(fragment in item["condition"] for fragment in allowed_branch_fragments)
        for item in branches
    )
    calls = set(source_path_calls(RUNNER))
    forbidden_calls = sorted(
        calls
        & {
            "blockwise_gate",
            "effective_bilateral",
            "select_block_action",
            "response_cost",
            "choose_response_actions",
        }
    )
    source = RUNNER.read_text(encoding="utf-8")
    command_contract_pass = all(
        token in source
        for token in (
            "NOMINAL_SPEED_MPS, 0.0, float(args.straight_wz)",
            '"robot_box_contacts": "observation-only; never a hard stop"',
            '"continuous_path_feedback": False',
            '"box_p_feedback": False',
            '"E2_QP": False',
            '"PPO": False',
        )
    )
    frozen_common_pass = bool(
        all(
            contract["official_falcon"]["sha256"] == OFFICIAL_FALCON_SHA256
            and contract["q_upper"]["sha256"] == Q_UPPER_SHA256
            and contract["command_contract"]["active_vx_mps"] == NOMINAL_SPEED_MPS
            and contract["command_contract"]["active_vy_mps"] == 0.0
            and contract["path_contract"]["start_xy_world_m"] == [1.8, 0.0]
            and contract["path_contract"]["yaw_rad"] == 0.0
            and contract["path_contract"]["absolute_checkpoints_m"] == [0.5 * i for i in range(1, 11)]
            for contract in contracts.values()
        )
        and abs(PHYSICS_DT_S - 0.005) < 1.0e-12
        and CONTROL_DECIMATION == 4
    )
    asset_records: dict[str, Any] = {}
    for formal in FORMAL_EE_VARIANTS:
        spec = ASSET_SPECS[formal]
        path = asset_path(REPO, formal)
        record: dict[str, Any] = {
            "path": str(path),
            "sha256": sha256_file(path),
            "expected_sha256": spec.sha256,
            "asset_sha_pass": path.is_file() and sha256_file(path) == spec.sha256,
            "expected_contact_bodies": list(spec.contact_body_expected),
            "rubber_hand_mass_per_side_kg": RUBBER_HAND_MASS_PER_SIDE_KG if spec.has_rubber_hand else None,
        }
        if spec.has_rubber_hand:
            mass = composed_rubber_hand_mass(path)
            closure = {side: composed_fixed_joint_closure(path, side) for side in ("left", "right")}
            record["mass_pass"] = bool(mass["mass_pass"])
            record["closure_pass"] = bool(all(item["pass"] for item in closure.values()))
            record["mass"] = mass
            record["closure"] = closure
        else:
            record["mass_pass"] = True
            record["closure_pass"] = True
        asset_records[formal] = record

    provenance = None
    if args.provenance_reference.resolve().is_file():
        provenance = json.loads(args.provenance_reference.resolve().read_text(encoding="utf-8"))
    provenance_pass = bool(provenance is not None and provenance.get("PROVENANCE_PASS", False))

    report: dict[str, Any] = {
        "schema": "FALCON_FUNCTIONAL_BLOCKWISE_VARIANT_CONTRACT_AUDIT.v1",
        "task": "FALCON_FUNCTIONAL_REAUDIT_PREDICTIVE_STOP_AND_5M_BLOCKWISE",
        "formal_ee_variants": list(FORMAL_EE_VARIANTS),
        "allowed_variant_differences": [
            "selected EE asset bytes and runtime body identity",
            "selected calibrated straight wz",
            "selected initial d_stop_hat from the corresponding measured probe",
            "endpoint/hand-specific posture and contact observation fields",
        ],
        "forbidden_variant_differences": [
            "FALCON ONNX, Golden q_upper, PD/history/joint mapping/action scale",
            "robot/box initial state, geometry, mass, friction, timestep/control rate",
            "nominal vx/vy, path start/yaw/checkpoint construction",
            "contact-based hard gates, continuous path feedback, E1/E2/QP/PPO",
        ],
        "frozen_input_hashes": frozen,
        "synthetic_contract_normalized_sha256": normalized_hashes,
        "all_normalized_contracts_identical": len(set(normalized_hashes.values())) == 1,
        "formal_source_branches": branches,
        "formal_branch_policy_pass": branch_policy_pass,
        "forbidden_controller_calls": forbidden_calls,
        "command_contract_source_pass": command_contract_pass,
        "frozen_common_contract_pass": frozen_common_pass,
        "assets": asset_records,
        "asset_contract_pass": all(
            item["asset_sha_pass"] and item["mass_pass"] and item["closure_pass"]
            for item in asset_records.values()
        ),
        "existing_composed_asset_provenance_reference": str(args.provenance_reference.resolve()),
        "existing_composed_asset_provenance_pass": provenance_pass,
        "runner_source_sha256": sha256_file(RUNNER),
        "baseline_runner_source_sha256": sha256_file(BASELINE_RUNNER),
        "official_falcon_path": str(FALCON_ONNX),
        "q_upper_path": str(Q_UPPER_PATH),
        "ABC_OTHER_THAN_EE_DIFFERENCE_PASS": bool(
            len(set(normalized_hashes.values())) == 1
            and branch_policy_pass
            and not forbidden_calls
            and command_contract_pass
            and frozen_common_pass
            and all(
                item["asset_sha_pass"] and item["mass_pass"] and item["closure_pass"]
                for item in asset_records.values()
            )
            and provenance_pass
        ),
    }
    report["report_sha256"] = digest(report)
    output.write_text(json.dumps(canonical(report), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(canonical(report), indent=2, sort_keys=True), flush=True)
    try:
        app.close(wait_for_replicator=False, skip_cleanup=False)
    except Exception:
        pass
    return 0 if report["ABC_OTHER_THAN_EE_DIFFERENCE_PASS"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
